osx_image: xcode7.2
language: objective-c
cache: cocoapods
xcode_workspace: Spectacle.xcworkspace
xcode_scheme: Spectacle

rvm: 2.2.2

before_install:
  - gem install cocoapods -v '0.39.0'

before_script:
  - export LANG=en_US.UTF-8

script:
  - xctool -workspace Spectacle.xcworkspace -scheme Spectacle test
